spring:
  datasource:
    hikari:
      pool-name: eshkere
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      validation-timeout: 5000
      connection-init-sql: "SELECT 1"
      leak-detection-threshold: 2000