services:
  redis:
    image: redis:latest
    restart: on-failure
    container_name: local-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres-local
    volumes:
      - ~/volumes/postgres-data:/var/lib/postgresql/data
      - ./db-init-migration:/docker-entrypoint-initdb.d
    ports:
      - "1232:5432"
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOST: 127.0.0.1
      KC_HTTP_ENABLED: true
      #      KC_FRONTEND_URL: https://id.myislab.ru:8443
      KC_HOSTNAME_STRICT: false
      KC_HTTP_PORT: 8080
      #      KC_IMPORT: /opt/keycloak/data/import/realm.json
      KC_PROXY_HEADERS: xforwarded
      KC_METRICS_ENABLED: true
      PROXY_ADDRESS_FORWARDING: true
      #      CERTIFICATE_FILE: /etc/ssl/certs/tls.crt
      #      CERTIFICATE_KEY: /etc/ssl/certs/tls.key
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN_EMAIL: admin@myislab.ru
    #      KEYCLOAK_CLIENT_SECRET: clientSecret
    ports:
      - "0.0.0.0:8444:8080"
      - "0.0.0.0:8443:8443"
      - "127.0.0.1:9228:9000"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 10s
      timeout: 10s
      start_period: 15s
      retries: 5
    command:
      - "start-dev"
      #      - "--hostname=https://id.myislab.ru:8443"
      #      - "--import-realm"
      #      - "--https-certificate-file=/etc/ssl/certs/tls.crt"
      #      - "--https-certificate-key-file=/etc/ssl/certs/tls.key"
      - "--metrics-enabled=true"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs